apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: innovation-poi-map-app-dev
  annotations:
    argocd/app-name: innovation-poi-map-app-dev
    backstage.io/kubernetes-id: innovation-poi-map-app
    backstage.io/kubernetes-namespace: innovation
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-aro24/innovation-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.kovj5vhc.eastus.aroapp.io/dev-pipelines/ns/innovation/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.kovj5vhc.eastus.aroapp.io/k8s/ns/innovation/deployments/innovation-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.kovj5vhc.eastus.aroapp.io/#https://github.com/rhdh-aro24/innovation-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://innovation-poi-map-app-innovation.apps.kovj5vhc.eastus.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:julianbueno"
  system: workshop-system-innovation
  consumesApis:
    - gateway-api-innovation
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-innovation
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:julianbueno"
